# Generated by Django 5.2 on 2025-04-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_created_date_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='created_by',
        ),
    ]
